title: Auditor-General's Office
url: https://www.ago.gov.sg
favicon: /images/LogoFavicon.png
colors:
  primary-color: "#080cbd"
  secondary-color: "#0941b5"
  media-colors:
    - title: media-color-one
      color: "#0e1984"
    - title: media-color-two
      color: "#2241ee"
    - title: media-color-three
      color: "#1418e2"
    - title: media-color-four
      color: "#1913ca"
    - title: media-color-five
      color: "#2033b1"
resources_name: Resources
description: Auditor-General's Office
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d3kwoowvdm5w35.amplifyapp.com/
prod: https://master.d3kwoowvdm5w35.amplifyapp.com/
shareicon: /images/AGOlogo.png
is_government: true
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
